# Assignment 3 - Individual Capstone Assessment

## Introduction
From my perspective, the senior design project is all about applying all of the knowledge I have accrued over the past five years, from my coursework and my co-ops and using it to create a unique, challenging project that will display my skills as a programmer in the Computer Science field. Coming into college, I was not a strong programmer by any means, I took one course in high school and did not do very well in it. After these 5 years I feel much more comfortable programming and can say that I am ready to show off my skills and apply what I have learned. Me and my team are going to really test what we know and put our minds together and really see what we can do as a collective. I have been working with these guys as colleagues and hanging out with them as friends and I am excited to see what we can accomplish. This project will encourage lots of teamwork and will be a great stepping stone from one project to the next as I further myself into my career as a computer science student.

## College Curriculum
Throughout my time studying at the University of Cincinnati, I have learned many different skills for programming and for my professional career. One of the courses that got the ball rolling for me was Data Structures (CS2028C). This course we learned all about the many different data structures that programmers use while creating solutions for employers and projects. We learned the ins and outs of each one and built them from scratch to fully understand them in C++, this is when I really started to feel comfortable as a programmer and really start to apply my skills. Throughout my coursework, I have learned how to pick away at a problem and to think of different strategies for solving them. Programming is one of those things where you can get stuck and frustrated very easily but can be rewarding and if you work hard at any problem and use critical thinking, you seem to find the solution. I expect to apply these skills to create a product that I am proud of and a product people would have an enjoyable to use and is easy to understand. 

## Co-op
I only managed to work 4 co-ops do to falling behind in coursework my freshman year, so landing that first co-op really meant a lot to me. My first co-op experience was at The Health Collaborative, a health information exchange (HIE) located here in Cincinnati about 5 minutes away from campus. I was an Informatics Intern and during my first semester a developed a tool in Python that would convert an HL7 formatted file into a human readable format for my coworkers who had to look at these messages all day. It featured  search tools, highlighting, basic analytics, and other neat methods. That was the first project I ever really worked on so that was when I really first learned how to program because beforehand I was not very confident with what I was doing and didn't understand exactly what I was doing. My next co-op rotation was at Emerson Commercial and Residential Solutions located in Sidney, OH, about 90 minutes north of Cincinnati. I was a Swift developer my first term and an Android developer my second term working on a mobile application for them. For the Swift term I learned a lot about building UI using SwiftUI and what it means to be apart of a team, creating a project. I did some minor back-end things but was mainly front-end. When I returned to work on the Android application, I did full-stack development in Kotlin and applied what I learned from the iOS app into building the Android one. I worked on interacting with the Modbus to push data through bluetooth and read it back to the phone. From my 4 terms of co-op, I learned a lot about working as a team, becoming a stronger programmer, and being a professional. I will use this skills I have acquired to work cohesively with my team to create a great product.

## Project Motivation
I believe I speak for me and my group when I say this, I think we are all very excited to work on this project. We all have a solid interest with Finance whether that is stocks, crypto, investments, and so on. My Dad is a portfolio manager and I think making this tool is something I could show him and he will appreciate something I have done and something he will understand. I myself have been trying to invest my money more and this tool we will create will certainly help out. I expect we are going to make a product we are all proud of and a product that other people can use and will enjoy themselves. I expect our project will include multiple tools to help users to see some financial advice that will benefit them and will do some analytics for some deeper analysis.

## Project Approach
My group and my project will be some form of web application. We are going to have to come up with our collective goals and methods of achieving them via what frameworks we are going to use, how are we gonna work on this project together, i.e. weekly meetings, sprints, and so on, and of course how to split up the work. I will evaluate my contributions based on asking my team about what I have worked on and if there are ways I can improve it, I will test out my work for bugs and solving the ones that come up. I will know I have done a good job once my partners and I have created something that is functional, looks elegant, and we can show to someone else and they are impressed by it. Anything else, I would not feel comfortable saying I have done a good job. I plan on trying to help the project in any way I can and really try and step up. I would love for this project to turn out really well and see where it can take each of us in our careers whether that is land another job or inspires us to make something better.