services:
  
  frontend:
    build: ./frontend
    command: sh -c "npm install && node_modules/.bin/ng serve --proxy-config proxy.conf.json --port 4200 --host 0.0.0.0 --disable-host-check true"
    ports:
      - '4200:4200'
    working_dir: /root/frontend
    volumes:
      - ./frontend:/root/frontend:cached

  backend:
    build: ./backend  # path to Dockerfile
    command: sh -c "pip install  --no-cache-dir -r requirements.txt && python run.py"
    environment:
      - PYTHONUNBUFFERED=1  # displays python output
    ports:
      - '5000:5000'  # host:container
    working_dir: /root/backend
    volumes:
      - ./backend:/root/backend:cached  # map local disk to container